version: '3.9'

services:
  alpine-stack:
    image: alpine:3.14
    volumes:
      - "./localstack:/utils"
    command: >
      sed -i -e 's/\r$$//' /utils/docker-entrypoint.sh

  localstack:
    image: localstack/localstack:2.3.0
    container_name: localstack
    depends_on:
      - alpine-stack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - ./localstack/:/opt/localstack/
      - ./localstack/docker-entrypoint.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318

  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  customer-api:
    build: ./energy-sa-customer/
    restart: on-failure
    depends_on:
      - localstack
    environment:
       SPRING_CLOUD_AWS_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_S3_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_S3_PATH_STYLE_ACCESS_ENABLED: true
       OTL_GRPC_SPAN_EXPORTER_URL: http://jaeger:4317
    ports:
      - 8093:8093

  invoice-api:
    build: ./energy-sa-invoice/
    restart: on-failure
    depends_on:
      - localstack
    environment:
       SPRING_CLOUD_AWS_SQS_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_S3_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_S3_PATH_STYLE_ACCESS_ENABLED: true
       OTL_GRPC_SPAN_EXPORTER_URL: http://jaeger:4317
    ports:
      - 8092:8092

  report-api:
    build: ./energy-sa-report/
    restart: on-failure
    depends_on:
      - localstack
      - invoice-api
      - customer-api
    environment:
       SPRING_CLOUD_AWS_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_PARAMETERSTORE_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_SECRETSMANAGER_ENDPOINT: http://localstack:4566
       SPRING_CLOUD_AWS_DYNAMODB_ENDPOINT: http://localstack:4566
       OTL_GRPC_SPAN_EXPORTER_URL: http://jaeger:4317
       INVOICE_API_URL: http://invoice-api:8092
       CUSTOMER_API_URL: http://customer-api:8093
    ports:
      - 8094:8094

  grafana:
    image: grafana/grafana:latest
    restart: on-failure
    depends_on:
      - prometheus
    environment:
       GF_SECURITY_ADMIN_PASSWORD: 123r
    ports:
      - 3000:3000
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards/