{
 "title": "Energy Customer SA Golden Signals",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Saturação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_cpu_usage{job=\"energy-sa-customer\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória (JVM)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"energy-sa-customer\"}) / sum(jvm_memory_max_bytes{area=\"heap\", job=\"energy-sa-customer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Taxa de Tráfego", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "2x Criação cliente",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"2..\", method=\"POST\", uri=\"/customers\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"POST\", uri=\"/customers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2x Obter cliente por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"2..\", method=\"GET\", uri=\"/customers/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"GET\", uri=\"/customers/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Taxa de Erro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "5x Obter cliente por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"5..\", method=\"GET\", uri=\"/customers/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"GET\", uri=\"/customers/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5x Criação de cliente",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"5..\", method=\"POST\", uri=\"/customers\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"POST\", uri=\"/customers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4x Obter cliente por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"4..\", method=\"GET\", uri=\"/customers/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"GET\", uri=\"/customers/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4x Criação de cliente",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", status=~\"4..\", method=\"POST\", uri=\"/customers\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-customer\", method=\"POST\", uri=\"/customers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latência", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Busca cliente por Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(http_server_requests_seconds_max{job=\"energy-sa-customer\", uri=\"/customers/{id}\", method=\"GET\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Criação de cliente",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(http_server_requests_seconds_max{job=\"energy-sa-customer\", uri=\"/customers\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}