{
 "title": "Energy Invoice SA Golden Signals",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Saturação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (process_cpu_usage{job=\"energy-sa-invoice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória (JVM)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"energy-sa-invoice\"}) / sum(jvm_memory_max_bytes{area=\"heap\", job=\"energy-sa-invoice\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Taxa de Tráfego", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "2x Obter conta por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"2..\", method=\"GET\", uri=\"/invoices/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2x Obter contas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"2..\", method=\"GET\", uri=\"/invoices\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Taxa de Erro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "5x Obter conta por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"5..\", method=\"GET\", uri=\"/invoices/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5x Obter contas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"5..\", method=\"GET\", uri=\"/invoices\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4x Obter conta por Id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"4..\", method=\"GET\", uri=\"/invoices/{id}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices/{id}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4x Obter contas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", status=~\"4..\", method=\"GET\", uri=\"/invoices\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"energy-sa-invoice\", method=\"GET\", uri=\"/invoices\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latência", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Busca conta por Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(http_server_requests_seconds_max{job=\"energy-sa-invoice\", uri=\"/invoices/{id}\", method=\"GET\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Obter contas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(http_server_requests_seconds_max{job=\"energy-sa-invoice\", uri=\"/invoices\", method=\"GET\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}