global:
  scrape_interval:  5s # Set the global default scrape interval to every  5 seconds.

scrape_configs:
  - job_name: 'energy-sa-report'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['report-api:8094']

  - job_name: 'energy-sa-invoice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['invoice-api:8092']

  - job_name: 'energy-sa-customer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-api:8093']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']