global:
  scrape_interval:  5s # Set the global default scrape interval to every  5 seconds.

scrape_configs:
  - job_name: 'energy-sa-report'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8094']

  - job_name: 'energy-sa-invoice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8092']

  - job_name: 'energy-sa-customer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8093']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']